### ISSUE TITLE
Weird Error when player's getting hit

### ISSUE THREAD

**Issue by LeSuriKat** [TeamUlysses/ulib#59]
### Steps to reproduce
1. Be on the server
2. Get hit

### Expected behavior
There should be no error and every EntityTakeDamage hook should apply normaly

### Actual behavior
I've got the following erros and some hooks seems to be stopped

### Error(s) in server console, if any
![image](https://user-images.githubusercontent.com/57335422/68521817-1dbce700-02a5-11ea-86a3-61c5ad6ea8f3.png)

![image](https://user-images.githubusercontent.com/57335422/68521824-30372080-02a5-11ea-9183-eeb308f81ad8.png)

![image](https://user-images.githubusercontent.com/57335422/68521827-34fbd480-02a5-11ea-9554-6f02e3f2adb7.png)

(I've put different ones, just in case it's usefull for you guys)

### Error(s) in player's console, if any
[ERROR] addons/adminmenu/lua/autorun/client/staff_cl.lua:155: attempt to concatenate a nil value
  1. fn - addons/adminmenu/lua/autorun/client/staff_cl.lua:155
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

### Version
ULib v2.63d (05/12/18)
ULX v3.73 (05/21/18)

PS : Thanks for your time, and sorry if it's stupid or already solved somewhere, I really searched hard by myself...

**Comment by Nayruden** [comment]
ULib changes the default GMod hook behavior, so that's why you're seeing ULib mentioned in the stack trace. Unfortunately, none of the other code on your stack trace is something we have any control over, and the manner in which this author hooked into this event is definitely odd -- that's why you're seeing that long string that starts with a comment. This is sometimes a technique used by exploits... so I'd definitely recommend checking your server for any suspicious addons. Regardless, you're going to have to remove your addons one by one (or add them back in one by one) to figure out which addon is responsible for this error.
